cache:
  directories:
  - $HOME/.m2
dist: trusty
language: java
branches:
  only:
  - youness/feature
  - develop
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "younessfathi"
    token:
      secure: "3277a5d8b47e87c2a9480090832ff61697ab1880"
script:
- mvn -B clean verify sonar:sonar -Dsonar.login=3277a5d8b47e87c2a9480090832ff61697ab1880 -Dsonar.projectKey=younessFathi_crafts -Dsonar.organization=younessfathi